# Generated by Django 5.2.7 on 2025-10-21 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('source', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('cost', models.IntegerField(default=0)),
                ('descriptors', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('range', models.CharField(default='', max_length=50)),
                ('target', models.CharField(default='', max_length=50)),
                ('attack', models.CharField(default='', max_length=50)),
                ('trigger', models.CharField(default='', max_length=50)),
                ('hit', models.TextField(default='')),
                ('miss', models.TextField(default='')),
                ('effect', models.TextField(default='')),
                ('special', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('ability_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ability')),
                ('category', models.CharField(default='', max_length=20)),
                ('level', models.CharField(default='', max_length=20)),
                ('components', models.CharField(default='', max_length=20)),
            ],
            bases=('api.ability',),
        ),
    ]
