# Generated by Django 5.2.7 on 2026-01-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('name', models.CharField(default='', max_length=1, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Origem', 'Origem'), ('Categoria', 'Categoria'), ('Equipamento', 'Equipamento'), ('Dano', 'Dano'), ('Diversos', 'Diversos')], default='', max_length=20)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationType',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.SmallIntegerField(default=0)),
                ('type', models.ManyToManyField(related_name='modification_types', to='api.modificationtype')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('source', models.CharField(choices=[('Livro Básico', 'Livro Básico')], default='Livro Básico', max_length=50)),
                ('execution_type', models.CharField(choices=[('Ação', 'Ação'), ('Ação Bonus', 'Ação Bonus'), ('Reação', 'Reação'), ('Ação Livre', 'Ação Livre'), ('Passiva', 'Passiva'), ('Mais que uma Ação', 'Mais que uma Ação')], default='Ação', max_length=20)),
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('cost', models.SmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('range', models.SmallIntegerField(default=0)),
                ('target', models.CharField(default='', max_length=50)),
                ('duration', models.CharField(choices=[('Instantânea', 'Instantânea'), ('Uma cena (Concentração)', 'Uma cena (Concentração)'), ('Uma cena', 'Uma cena'), ('Até o final do próximo descanso', 'Até o final do próximo descanso'), ('Até o final do próximo descanso longo', 'Até o final do próximo descanso longo'), ('Até o final do turno', 'Até o final do turno'), ('8 horas', '8 horas'), ('24 horas', '24 horas'), ('Concentração', 'Concentração')], default='Instantânea', max_length=50)),
                ('attack', models.CharField(blank=True, choices=[('Força', 'FOR'), ('Destreza', 'DES'), ('Constituição', 'CON'), ('Inteligência', 'INT'), ('Sabedoria', 'SAB'), ('Carisma', 'CAR')], default='FOR', max_length=50, null=True)),
                ('trigger', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('hit', models.TextField(blank=True, default='', null=True)),
                ('miss', models.TextField(blank=True, default='', null=True)),
                ('effect', models.TextField(default='')),
                ('special', models.TextField(blank=True, default='', null=True)),
                ('descriptors', models.ManyToManyField(related_name='%(class)s_descriptors', to='api.descriptor')),
                ('modifications', models.ManyToManyField(blank=True, related_name='%(class)s_modifications', to='api.modification')),
            ],
            options={
                'db_table': 'api_ability',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('source', models.CharField(choices=[('Livro Básico', 'Livro Básico')], default='Livro Básico', max_length=50)),
                ('execution_type', models.CharField(choices=[('Ação', 'Ação'), ('Ação Bonus', 'Ação Bonus'), ('Reação', 'Reação'), ('Ação Livre', 'Ação Livre'), ('Passiva', 'Passiva'), ('Mais que uma Ação', 'Mais que uma Ação')], default='Ação', max_length=20)),
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('cost', models.SmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('range', models.SmallIntegerField(default=0)),
                ('target', models.CharField(default='', max_length=50)),
                ('duration', models.CharField(choices=[('Instantânea', 'Instantânea'), ('Uma cena (Concentração)', 'Uma cena (Concentração)'), ('Uma cena', 'Uma cena'), ('Até o final do próximo descanso', 'Até o final do próximo descanso'), ('Até o final do próximo descanso longo', 'Até o final do próximo descanso longo'), ('Até o final do turno', 'Até o final do turno'), ('8 horas', '8 horas'), ('24 horas', '24 horas'), ('Concentração', 'Concentração')], default='Instantânea', max_length=50)),
                ('attack', models.CharField(blank=True, choices=[('Força', 'FOR'), ('Destreza', 'DES'), ('Constituição', 'CON'), ('Inteligência', 'INT'), ('Sabedoria', 'SAB'), ('Carisma', 'CAR')], default='FOR', max_length=50, null=True)),
                ('trigger', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('hit', models.TextField(blank=True, default='', null=True)),
                ('miss', models.TextField(blank=True, default='', null=True)),
                ('effect', models.TextField(default='')),
                ('special', models.TextField(blank=True, default='', null=True)),
                ('category', models.CharField(choices=[('Controle', 'Controle'), ('Ofensivo', 'Ofensivo'), ('Utilitário', 'Utilitário')], default='Controle', max_length=20)),
                ('layer', models.CharField(choices=[('Truque', 'Truque'), ('Superficial', 'Superficial'), ('Rasa', 'Rasa'), ('Profunda', 'Profunda')], default='Truque', max_length=20)),
                ('components', models.ManyToManyField(related_name='components', to='api.component')),
                ('descriptors', models.ManyToManyField(related_name='%(class)s_descriptors', to='api.descriptor')),
                ('modifications', models.ManyToManyField(blank=True, related_name='%(class)s_modifications', to='api.modification')),
            ],
            options={
                'db_table': 'api_spell',
            },
        ),
    ]
