# Generated by Django 5.2.7 on 2025-10-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='spell',
            name='level',
        ),
        migrations.AddField(
            model_name='ability',
            name='duration',
            field=models.CharField(choices=[('Instantânea', 'Instantânea'), ('Concentração', 'Concentração')], default='Instantânea', max_length=20),
        ),
        migrations.AddField(
            model_name='ability',
            name='execution_type',
            field=models.CharField(choices=[('Ação', 'Ação'), ('Ação Bonus', 'Ação Bonus'), ('Reação', 'Reação'), ('Ação Livre', 'Ação Livre'), ('Passiva', 'Passiva'), ('Mais que uma Ação', 'Mais que uma Ação')], default='Ação', max_length=20),
        ),
        migrations.AddField(
            model_name='spell',
            name='layer',
            field=models.CharField(choices=[('Truque', 'Truque'), ('Superficial', 'Superficial'), ('Rasa', 'Rasa'), ('Profunda', 'Profunda')], default='Truque', max_length=20),
        ),
        migrations.AlterField(
            model_name='ability',
            name='attack',
            field=models.CharField(blank=True, choices=[('Força', 'FOR'), ('Destreza', 'DES'), ('Constituição', 'CON'), ('Inteligência', 'INT'), ('Sabedoria', 'SAB'), ('Carisma', 'CAR')], default='FOR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='cost',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ability',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.RemoveField(
            model_name='ability',
            name='descriptors',
        ),
        migrations.AlterField(
            model_name='ability',
            name='hit',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='miss',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='range',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ability',
            name='source',
            field=models.CharField(choices=[('Livro Básico', 'Livro Básico')], default='Livro Básico', max_length=50),
        ),
        migrations.AlterField(
            model_name='ability',
            name='special',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='trigger',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='category',
            field=models.CharField(choices=[('Controle', 'Controle'), ('Ofensivo', 'Ofensivo'), ('Utilitário', 'Utilitário')], default='Controle', max_length=20),
        ),
        migrations.AddField(
            model_name='ability',
            name='descriptors',
            field=models.ManyToManyField(related_name='abilities', to='api.descriptor'),
        ),
    ]
