# Generated by Django 5.2.7 on 2025-10-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_descriptor_remove_spell_level_ability_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptor',
            old_name='name',
            new_name='descriptor',
        ),
    ]
