# Generated by Django 5.2.7 on 2025-10-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_descriptor_descriptor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptor',
            old_name='descriptor',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='ability',
            name='descriptors',
            field=models.ManyToManyField(related_name='descriptors', to='api.descriptor'),
        ),
    ]
