# Generated by Django 5.2.7 on 2026-01-19 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_descriptor_descriptor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('name', models.CharField(default='', max_length=1, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationType',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='descriptor',
            name='category',
            field=models.CharField(choices=[('Origem', 'Origem'), ('Categoria', 'Categoria'), ('Equipamento', 'Equipamento'), ('Dano', 'Dano'), ('Diversos', 'Diversos')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ability',
            name='duration',
            field=models.CharField(choices=[('Instantânea', 'Instantânea'), ('Uma cena (Concentração)', 'Uma cena (Concentração)'), ('Uma cena', 'Uma cena'), ('Até o final do próximo descanso', 'Até o final do próximo descanso'), ('Até o final do próximo descanso longo', 'Até o final do próximo descanso longo'), ('Até o final do turno', 'Até o final do turno'), ('8 horas', '8 horas'), ('24 horas', '24 horas'), ('Concentração', 'Concentração')], default='Instantânea', max_length=50),
        ),
        migrations.RemoveField(
            model_name='spell',
            name='components',
        ),
        migrations.CreateModel(
            name='Modifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_ability', to='api.ability')),
                ('type', models.ManyToManyField(related_name='modification_types', to='api.modificationtype')),
            ],
        ),
        migrations.AddField(
            model_name='ability',
            name='modifications',
            field=models.ManyToManyField(blank=True, related_name='ability_modifications', to='api.modifications'),
        ),
        migrations.AddField(
            model_name='spell',
            name='components',
            field=models.ManyToManyField(related_name='components', to='api.component'),
        ),
    ]
