# Generated by Django 5.2.7 on 2025-10-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('ability_source', models.CharField(default='', max_length=50)),
                ('ability_name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('ability_cost', models.IntegerField(default=0)),
                ('ability_descriptors', models.CharField(default='', max_length=50)),
                ('ability_description', models.TextField(default='')),
                ('ability_range', models.CharField(default='', max_length=50)),
                ('ability_target', models.CharField(default='', max_length=50)),
                ('ability_attack', models.CharField(default='', max_length=50)),
                ('ability_trigger', models.CharField(default='', max_length=50)),
                ('ability_hit', models.TextField(default='')),
                ('ability_miss', models.TextField(default='')),
                ('ability_effect', models.TextField(default='')),
                ('ability_special', models.TextField(default='')),
            ],
        ),
    ]
