# Generated by Django 5.2.7 on 2025-10-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('ability_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_rest.ability')),
                ('category', models.CharField(default='', max_length=20)),
                ('level', models.CharField(default='', max_length=20)),
                ('components', models.CharField(default='', max_length=20)),
            ],
            bases=('api_rest.ability',),
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='ability_attack',
            new_name='attack',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='ability_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='ability_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='ability_descriptors',
            new_name='descriptors',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='ability_effect',
            new_name='effect',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='ability_hit',
            new_name='hit',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='ability_miss',
            new_name='miss',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='ability_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='ability_range',
            new_name='range',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='ability_source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='ability_special',
            new_name='special',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='ability_target',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='ability_trigger',
            new_name='trigger',
        ),
    ]
